export const FETCH_COUNTRY_STATS = 'FETCH_COUNTRY_STATS';
export const FETCH_COUNTRY_STATS_START = 'FETCH_COUNTRY_STATS_START';
export const FETCH_COUNTRY_STATS_SUCCESS = 'FETCH_COUNTRY_STATS_SUCCESS';
export const FETCH_COUNTRY_STATS_FAIL = 'FETCH_COUNTRY_STATS_FAIL';

export const FETCH_GLOBAL_STATS = 'FETCH_GLOBAL_STATS';
export const FETCH_GLOBAL_STATS_START = 'FETCH_GLOBAL_STATS_START';
export const FETCH_GLOBAL_STATS_SUCCESS = 'FETCH_GLOBAL_STATS_SUCCESS';
export const FETCH_GLOBAL_STATS_FAIL = 'FETCH_GLOBAL_STATS_FAIL';
